version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: rustoutboxsweeper-postgres
    environment:
      POSTGRES_USER: sweeper
      POSTGRES_PASSWORD: sweeperpass
      POSTGRES_DB: sweeperdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rustoutboxsweeper:
    image: rustoutboxsweeper
    build: .
    container_name: rustoutboxsweeper-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://sweeper:sweeperpass@postgres:5432/sweeperdb
      AWS_REGION: eu-west-1
      SWEEP_INTERVAL_MS: 5000
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      BATCH_SIZE: 10
    ports:
      - "8080:8080"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      # LocalStack Gateway
      - "127.0.0.1:4566:4566"
      # External services port range
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      # You can add configuration variables here
      - DEBUG=${DEBUG:-0}
    volumes:
      # Mounts a volume for persistence
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      # Mounts the docker socket to allow LocalStack to spin up other containers (e.g., for Lambda)
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  pgdata: